package com.aistudio.epubedit.kqptxy.util

object Loc {
    private val ru = mapOf(
        "app_name" to "EpubEdit",
        "no_titles" to "Нет добавленных тайтлов",
        "press_add_button" to "Нажмите на кнопку + , чтобы создать новый проект",
        "new_title" to "Новый тайтл",
        "enter_title" to "Введите название книжного проекта или оригинального тайтла:",
        "title_label" to "Название тайтла",
        "title_placeholder" to "Например: Beyond the Event Horizon",
        "create" to "Создать",
        "cancel" to "Отмена",
        "delete_title" to "Удалить тайтл",
        "no_author" to "Автор не указан",
        "created_at" to "Создан: ",
        "add_title" to "Добавить тайтл",
        "settings" to "Настройки",
        "language" to "Язык",
        "english" to "English (Английский)",
        "russian" to "Русский (Russian)",
        "auto_close" to "Автозакрытие HTML-тегов",
        "close" to "Закрыть",
        // Details tabs and fields
        "tab_files" to "Файлы",
        "tab_chapters" to "Главы",
        "tab_info" to "Инфо",
        "tab_stats" to "Статистика",
        "back" to "Назад",
        "save" to "Сохранить",
        // Editor
        "visual" to "Визуально",
        "html_code" to "HTML код",
        "words" to "Слов",
        "chapter_text" to "ТЕКСТ ГЛАВЫ",
        "chapter_html" to "HTML-КОД ГЛАВЫ",
        "chapter_title" to "НАЗВАНИЕ ГЛАВЫ",
        "bold" to "Жирный",
        "italic" to "Курсив",
        "underlined" to "Подчеркнутый",
        "strikethrough" to "Зачеркнутый",
        "paragraph" to "Абзац",
        "stats_words" to "Всего слов",
        "stats_chars" to "Всего символов",
        "preview" to "Предпросмотр",
        "illustration_added" to "Иллюстрация добавлена",
        "illustration_error" to "Ошибка сохранения иллюстрации",
        "chapter_saved" to "Глава сохранена!",
        "unsaved_changes" to "Несохраненные изменения",
        "unsaved_changes_msg" to "Вы действительно хотите выйти? Все несохраненные изменения в главе будут потеряны.",
        "exit" to "Выйти",
        "delete_illustration" to "Удалить иллюстрацию?",
        "delete_illustration_msg" to "Вы действительно хотите удалить эту иллюстрацию из главы?",
        "illustration_deleted" to "Иллюстрация удалена",
        "delete" to "Удалить",
        "epub_editor" to "Редактор ePub",
        "save_upper" to "СОХРАНИТЬ",
        "insert_image" to "Вставить картинку",
        "exit_fullscreen" to "Выйти из полного экрана",
        "enter_fullscreen" to "На весь экран",
        "enter_text_here" to "Введите текст здесь...",
        "enter_html_here" to "<h2>Заголовок</h2>\n<p>Введите HTML код...</p>",
        "selected_items" to "Выделено элементов: ",
        "extra_chapters_deleted" to "Лишние главы удалены!",
        "keep_selected" to "Оставить выдел.",
        "selected_chapters_deleted" to "Выделенные главы удалены!",
        "delete_selected" to "Удалить выдел.",
        "new_chapter" to "Новая глава",
        "delete_chapter_q" to "Удалить главу?",
        "merging_volumes" to "Идет слияние томов...",
        "exporting_epub" to "Идет экспорт в EPUB...",
        "please_wait_export" to "Пожалуйста, подождите. Собираем главы и упаковываем книгу в итоговый файл EPUB.",
        "up" to "Вверх",
        "down" to "Вниз",
        "drag_to_move" to "Тяните для перемещения",
        "chars" to "симв.",
        "contains_illustrations" to "Содержит иллюстрации",
        "edit" to "Редактировать",
        "choose_cover" to "Выбрать обложку",
        "change" to "Изменить",
        "author_name" to "Имя автора / переводчика",
        "author" to "Автор",
        "output_file_name" to "Имя результирующего EPUB файла",
        "description" to "Описание / Синопсис",
        "no_description" to "Описание отсутствует...",
        "info_saved" to "Информация успешно сохранена!",
        "save_changes" to "Сохранить изменения",
        "exact_count" to "Точный подсчет",
        "without_html_tags" to "Без учета тегов HTML",
        "total_volume_weight" to "Общий вес томов",
        "input_volume_epub" to "Входной объем EPUB компонентов",
        "epub_components" to "Составляющие EPUB тома",
        "volume" to "Том ",
        "chapter_contribution" to "Вклад по главам (Слова)",
        "proportional_activity" to "Пропорциональная активность в последних разделах",
        "cover_illustration" to "Обложка тайтла",
        "auto_close_desc" to "Автоматически закрывать HTML-теги при вводе >",
        "enable_drag_drop" to "Перетаскивание зажатием",
        "drag_drop_desc" to "Зажмите элемент между кнопками, чтобы полноценно перетаскивать его",
        "theme" to "Тема приложения",
        "theme_light" to "Светлая",
        "theme_dark" to "Темная",
        "theme_amoled" to "AMOLED",
        "chapter_illustration" to "Иллюстрация главы",
        "formatting_only_html" to "Форматирование доступно при переключении на вкладку HTML-кода главы.",
        "illustration_empty_line_only" to "Иллюстрацию можно вставить только на пустую строку!",
        "image_not_found_local" to "Изображение не найдено локально",
        "file_label" to "Файл: ",
        "image_load_error" to "Ошибка загрузки изображения",
        "delete_illustration_cd" to "Удалить иллюстрацию"
    )

    private val en = mapOf(
        "app_name" to "EpubEdit",
        "no_titles" to "No titles added",
        "press_add_button" to "Tap the + button to create a new project",
        "new_title" to "New Title",
        "enter_title" to "Enter the book project name or original title:",
        "title_label" to "Title Name",
        "title_placeholder" to "For example: Beyond the Event Horizon",
        "create" to "Create",
        "cancel" to "Cancel",
        "delete_title" to "Delete Title",
        "no_author" to "Author not specified",
        "created_at" to "Created: ",
        "add_title" to "Add title",
        "settings" to "Settings",
        "language" to "Language",
        "english" to "English (Английский)",
        "russian" to "Русский (Russian)",
        "auto_close" to "Auto-close HTML tags",
        "close" to "Close",
        // Details tabs and fields
        "tab_files" to "Files",
        "tab_chapters" to "Chapters",
        "tab_info" to "Info",
        "tab_stats" to "Statistics",
        "back" to "Back",
        "save" to "Save",
        // Editor
        "visual" to "Visual",
        "html_code" to "HTML Code",
        "words" to "Words",
        "chapter_text" to "CHAPTER TEXT",
        "chapter_html" to "CHAPTER HTML",
        "chapter_title" to "CHAPTER TITLE",
        "bold" to "Bold",
        "italic" to "Italic",
        "underlined" to "Underlined",
        "strikethrough" to "Strikethrough",
        "paragraph" to "Paragraph",
        "stats_words" to "Total words",
        "stats_chars" to "Total characters",
        "preview" to "Preview",
        "illustration_added" to "Illustration added",
        "illustration_error" to "Error saving illustration",
        "chapter_saved" to "Chapter saved!",
        "unsaved_changes" to "Unsaved changes",
        "unsaved_changes_msg" to "Are you sure you want to exit? All unsaved changes will be lost.",
        "exit" to "Exit",
        "delete_illustration" to "Delete illustration?",
        "delete_illustration_msg" to "Are you sure you want to delete this illustration from the chapter?",
        "illustration_deleted" to "Illustration deleted",
        "delete" to "Delete",
        "epub_editor" to "ePub Editor",
        "save_upper" to "SAVE",
        "insert_image" to "Insert Image",
        "exit_fullscreen" to "Exit fullscreen",
        "enter_fullscreen" to "Enter fullscreen",
        "enter_text_here" to "Enter text here...",
        "enter_html_here" to "<h2>Title</h2>\n<p>Enter HTML code...</p>",
        "selected_items" to "Selected items: ",
        "extra_chapters_deleted" to "Extra chapters deleted!",
        "keep_selected" to "Keep selected",
        "selected_chapters_deleted" to "Selected chapters deleted!",
        "delete_selected" to "Delete selected",
        "new_chapter" to "New chapter",
        "delete_chapter_q" to "Delete chapter?",
        "merging_volumes" to "Merging volumes...",
        "exporting_epub" to "Exporting to EPUB...",
        "please_wait_export" to "Please wait. Assembling chapters and packing to final EPUB.",
        "up" to "Up",
        "down" to "Down",
        "drag_to_move" to "Drag to move",
        "chars" to "chars",
        "contains_illustrations" to "Contains illustrations",
        "edit" to "Edit",
        "choose_cover" to "Choose cover",
        "change" to "Change",
        "author_name" to "Author / Translator name",
        "author" to "Author",
        "output_file_name" to "Output EPUB file name",
        "description" to "Description / Synopsis",
        "no_description" to "No description available...",
        "info_saved" to "Information saved successfully!",
        "save_changes" to "Save changes",
        "exact_count" to "Exact count",
        "without_html_tags" to "Excluding HTML tags",
        "total_volume_weight" to "Total volumes weight",
        "input_volume_epub" to "Input volume of EPUB components",
        "epub_components" to "EPUB Volume Components",
        "volume" to "Volume ",
        "chapter_contribution" to "Chapter contribution (Words)",
        "proportional_activity" to "Proportional activity in last sections",
        "cover_illustration" to "Title cover",
        "auto_close_desc" to "Automatically insert closing tags when typing >",
        "enable_drag_drop" to "Enable Drag and Drop",
        "drag_drop_desc" to "Long press to reorder items",
        "theme" to "App Theme",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "theme_amoled" to "AMOLED",
        "chapter_illustration" to "Chapter illustration",
        "formatting_only_html" to "Formatting is available by switching to the HTML code tab.",
        "illustration_empty_line_only" to "Illustrations can only be inserted on an empty line!",
        "image_not_found_local" to "Image not found locally",
        "file_label" to "File: ",
        "image_load_error" to "Image loading error",
        "delete_illustration_cd" to "Delete illustration"
    )

    fun t(key: String, lang: String): String {
        val dictionary = if (lang == "en") en else ru
        return dictionary[key] ?: ru[key] ?: key
    }
}
